- name: Define credentials, if error update AnsibleCredential status then end play
  block:
    - name: Create Credential
      awx.awx.credential:
        name: "{{ lookup('env','CREDENTIAL_NAME') | default('present')  }}"
        description: "{{ lookup('env','CREDENTIAL_DESCRIPTION') }}"
        organization: "{{ lookup('env','CREDENTIAL_ORGANIZATION') }}"
        credential_type: "{{ lookup('env','CREDENTIAL_TYPE') }}"
        inputs: "{{ lookup('env','CREDENTIAL_INPUTS') }}"
        state: "{{ lookup('env','CREDENTIAL_STATE') }}"
      register: credentials

  rescue:
    - name: Update status if creation resulted in an error
      operator_sdk.util.k8s_status:
        api_version: tower.ansible.com/v1alpha1
        kind: AnsibleCredential
        name: "{{ lookup('env', 'ANSIBLECREDENTIAL_NAME') }}"
        namespace: "{{ lookup('env', 'ANSIBLECREDENTIAL_NAMESPACE') }}"
        status:
          isFinished: true
          AnsibleCredentialsResult:
            status: "error"
    - name: End playbook run
      meta: end_play

- name: Update AnsibleCredential status
  operator_sdk.util.k8s_status:
    api_version: tower.ansible.com/v1alpha1
    kind: AnsibleCredential
    name: "{{ lookup('env', 'ANSIBLECREDENTIAL_NAME') }}"
    namespace: "{{ lookup('env', 'ANSIBLECREDENTIAL_NAMESPACE') }}"
    status:
      isFinished: true
      AnsibleCredentialsResult:
        changed: "{{ credentials.changed }}"
        failed: "{{ credentials.failed }}"
