- name: Define SSH credentials, if error update AnsibleCredential status then end play
  block:
    - name: Create SSH Credential
      awx.awx.credential:
        name: "{{ lookup('env','NAME') }}"
        description: "{{ lookup('env','DESCRIPTION') }}"
        organization: "{{ lookup('env','ORGANIZATION') }}"
        credential_type: "{{ lookup('env','TYPE') }}"
        inputs:
          ssh_key_data: "{{ lookup('env','SSH_SECRET') }}"
          username: "{{ lookup('env','SSH_USERNAME') }}"
        state: present
      register: credentials

  rescue:
    - name: Update status if creation resulted in an error
      operator_sdk.util.k8s_status:
        api_version: tower.ansible.com/v1alpha1
        kind: AnsibleCredential
        name: "{{ lookup('env', 'ANSIBLECREDENTIAL_NAME') }}"
        namespace: "{{ lookup('env', 'ANSIBLECREDENTIAL_NAMESPACE') }}"
        status:
          isFinished: true
          AnsibleCredentialsResult:
            status: "error"
    - name: End playbook run
      meta: end_play

- name: Update AnsibleCredential status
  operator_sdk.util.k8s_status:
    api_version: tower.ansible.com/v1alpha1
    kind: AnsibleCredential
    name: "{{ lookup('env', 'ANSIBLECREDENTIAL_NAME') }}"
    namespace: "{{ lookup('env', 'ANSIBLECREDENTIAL_NAMESPACE') }}"
    status:
      isFinished: true
      AnsibleCredentialsResult:
        changed: "{{ credentials.changed }}"
        failed: "{{ credentials.failed }}"
