# Prerequisite: a Workflow Job Template named "ExampleTowerWorkflow" must
# already exist, e.g. via config/samples/workflowtemplate/tower_v1alpha1_workflowtemplate.yaml
apiVersion: tower.ansible.com/v1alpha1
kind: AnsibleWorkflow
metadata:
  name: workflow
spec:
  workflow_template_name: ExampleTowerWorkflow
  connection_secret: awxaccess
  runner_pull_policy: IfNotPresent
