- name: Define credentials, if error update AnsibleCredential status then end play
  block:
    - name: Create Credential
      awx.awx.credential:
        name: "{{ lookup('env','CREDENTIAL_NAME') }}"
        description: "{{ lookup('env','CREDENTIAL_DESCRIPTION') }}"
        organization: "{{ lookup('env','CREDENTIAL_ORGANIZATION') }}"
        credential_type: "{{ lookup('env','CREDENTIAL_TYPE') }}"
        inputs: "{{ lookup('env','CREDENTIAL_INPUTS') }}"
        state: present
      register: credentials
  when:
    - lookup('env','SSH_SECRET') == ''
    - lookup('env','KUBERNETES_BEARER_TOKEN') == ''
    - lookup('env','USERNAME_SECRET') == ''
    - lookup('env','PASSWORD_SECRET') == ''
    - lookup('env','TOKEN_SECRET') == ''

  rescue:
    - name: Update status if creation resulted in an error
      k8s_status:
        api_version: tower.ansible.com/v1alpha1
        kind: AnsibleCredential
        name: "{{ lookup('env', 'ANSIBLECREDENTIAL_NAME') }}"
        namespace: "{{ lookup('env', 'ANSIBLECREDENTIAL_NAMESPACE') }}"
        status:
          isFinished: true
          AnsibleCredentialsResult:
            status: "error"
    - name: End playbook run
      meta: end_play

- name: Update AnsibleCredential status
  k8s_status:
    api_version: tower.ansible.com/v1alpha1
    kind: AnsibleCredential
    name: "{{ lookup('env', 'ANSIBLECREDENTIAL_NAME') }}"
    namespace: "{{ lookup('env', 'ANSIBLECREDENTIAL_NAMESPACE') }}"
    status:
      isFinished: true
      AnsibleCredentialsResult:
        changed: "{{ credentials.changed }}"
        failed: "{{ credentials.failed }}"
  when:
  - lookup('env','SSH_SECRET') == ''
  - lookup('env','KUBERNETES_BEARER_TOKEN') == ''
  - lookup('env','USERNAME_SECRET') == ''
  - lookup('env','PASSWORD_SECRET') == ''
  - lookup('env','TOKEN_SECRET') == ''

- name: Define SSH credentials, if error update AnsibleCredential status then end play
  block:
    - name: Create SSH Credential
      awx.awx.credential:
        name: "{{ lookup('env','CREDENTIAL_NAME') }}"
        description: "{{ lookup('env','CREDENTIAL_DESCRIPTION') }}"
        organization: "{{ lookup('env','CREDENTIAL_ORGANIZATION') }}"
        credential_type: "{{ lookup('env','CREDENTIAL_TYPE') }}"
        inputs:
          ssh_key_data: "{{ lookup('env','SSH_SECRET') }}"
          username: "{{ lookup('env','SSH_USERNAME') }}"
        state: present
      register: credentials
  when:
    - lookup('env','SSH_SECRET') != ''
    - lookup('env','KUBERNETES_BEARER_TOKEN') == ''
    - lookup('env','USERNAME_SECRET') == ''
    - lookup('env','PASSWORD_SECRET') == ''
    - lookup('env','TOKEN_SECRET') == ''

  rescue:
    - name: Update status if creation resulted in an error
      k8s_status:
        api_version: tower.ansible.com/v1alpha1
        kind: AnsibleCredential
        name: "{{ lookup('env', 'ANSIBLECREDENTIAL_NAME') }}"
        namespace: "{{ lookup('env', 'ANSIBLECREDENTIAL_NAMESPACE') }}"
        status:
          isFinished: true
          AnsibleCredentialsResult:
            status: "error"
    - name: End playbook run
      meta: end_play

- name: Update AnsibleCredential status
  k8s_status:
    api_version: tower.ansible.com/v1alpha1
    kind: AnsibleCredential
    name: "{{ lookup('env', 'ANSIBLECREDENTIAL_NAME') }}"
    namespace: "{{ lookup('env', 'ANSIBLECREDENTIAL_NAMESPACE') }}"
    status:
      isFinished: true
      AnsibleCredentialsResult:
        changed: "{{ credentials.changed }}"
        failed: "{{ credentials.failed }}"
  when:
    - lookup('env','SSH_SECRET') != ''
    - lookup('env','KUBERNETES_BEARER_TOKEN') == ''
    - lookup('env','USERNAME_SECRET') == ''
    - lookup('env','PASSWORD_SECRET') == ''
    - lookup('env','TOKEN_SECRET') == ''

- name: Define Bearer credentials, if error update AnsibleCredential status then end play
  block:
    - name: Create Bearer Credential
      awx.awx.credential:
        name: "{{ lookup('env','CREDENTIAL_NAME') }}"
        description: "{{ lookup('env','CREDENTIAL_DESCRIPTION') }}"
        organization: "{{ lookup('env','CREDENTIAL_ORGANIZATION') }}"
        credential_type: "{{ lookup('env','CREDENTIAL_TYPE') }}"
        inputs:
          bearer_token: "{{ lookup('env','KUBERNETES_BEARER_TOKEN') }}"
          host: "{{ lookup('env','KUBERNETES_API') }}"
          verify_ssl: False
        state: present
      register: credentials
  when:
    - lookup('env','KUBERNETES_BEARER_TOKEN') != ''
    - lookup('env','SSH_SECRET') == ''
    - lookup('env','USERNAME_SECRET') == ''
    - lookup('env','PASSWORD_SECRET') == ''
    - lookup('env','TOKEN_SECRET') == ''

  rescue:
    - name: Update status if creation resulted in an error
      k8s_status:
        api_version: tower.ansible.com/v1alpha1
        kind: AnsibleCredential
        name: "{{ lookup('env', 'ANSIBLECREDENTIAL_NAME') }}"
        namespace: "{{ lookup('env', 'ANSIBLECREDENTIAL_NAMESPACE') }}"
        status:
          isFinished: true
          AnsibleCredentialsResult:
            status: "error"
    - name: End playbook run
      meta: end_play

- name: Update AnsibleCredential status
  k8s_status:
    api_version: tower.ansible.com/v1alpha1
    kind: AnsibleCredential
    name: "{{ lookup('env', 'ANSIBLECREDENTIAL_NAME') }}"
    namespace: "{{ lookup('env', 'ANSIBLECREDENTIAL_NAMESPACE') }}"
    status:
      isFinished: true
      AnsibleCredentialsResult:
        changed: "{{ credentials.changed }}"
        failed: "{{ credentials.failed }}"
  when:
  - lookup('env','SSH_SECRET') == ''
  - lookup('env','KUBERNETES_BEARER_TOKEN') != ''
  - lookup('env','USERNAME_SECRET') == ''
  - lookup('env','PASSWORD_SECRET') == ''
  - lookup('env','TOKEN_SECRET') == ''

- name: Define username and password credential, if error update AnsibleCredential status then end play
  block:
    - name: Create Username and Password type Credential
      awx.awx.credential:
        name: "{{ lookup('env','CREDENTIAL_NAME') }}"
        description: "{{ lookup('env','CREDENTIAL_DESCRIPTION') }}"
        organization: "{{ lookup('env','CREDENTIAL_ORGANIZATION') }}"
        credential_type: "{{ lookup('env','CREDENTIAL_TYPE') }}"
        inputs:
          username: "{{ lookup('env','USERNAME_SECRET') }}"
          password: "{{ lookup('env','PASSWORD_SECRET') }}"
        state: present
      register: credentials
  when:
    - lookup('env','KUBERNETES_BEARER_TOKEN') == ''
    - lookup('env','SSH_SECRET') == ''
    - lookup('env','USERNAME_SECRET') != ''
    - lookup('env','PASSWORD_SECRET') != ''
    - lookup('env','TOKEN_SECRET') == ''

  rescue:
    - name: Update status if creation resulted in an error
      k8s_status:
        api_version: tower.ansible.com/v1alpha1
        kind: AnsibleCredential
        name: "{{ lookup('env', 'ANSIBLECREDENTIAL_NAME') }}"
        namespace: "{{ lookup('env', 'ANSIBLECREDENTIAL_NAMESPACE') }}"
        status:
          isFinished: true
          AnsibleCredentialsResult:
            status: "error"
    - name: End playbook run
      meta: end_play

- name: Update AnsibleCredential status
  k8s_status:
    api_version: tower.ansible.com/v1alpha1
    kind: AnsibleCredential
    name: "{{ lookup('env', 'ANSIBLECREDENTIAL_NAME') }}"
    namespace: "{{ lookup('env', 'ANSIBLECREDENTIAL_NAMESPACE') }}"
    status:
      isFinished: true
      AnsibleCredentialsResult:
        changed: "{{ credentials.changed }}"
        failed: "{{ credentials.failed }}"
  when:
  - lookup('env','SSH_SECRET') == ''
  - lookup('env','KUBERNETES_BEARER_TOKEN') == ''
  - lookup('env','USERNAME_SECRET') != ''
  - lookup('env','PASSWORD_SECRET') != ''
  - lookup('env','TOKEN_SECRET') == ''

- name: Define token credential, if error update AnsibleCredential status then end play
  block:
    - name: Create Username and Password type Credential
      awx.awx.credential:
        name: "{{ lookup('env','CREDENTIAL_NAME') }}"
        description: "{{ lookup('env','CREDENTIAL_DESCRIPTION') }}"
        organization: "{{ lookup('env','CREDENTIAL_ORGANIZATION') }}"
        credential_type: "{{ lookup('env','CREDENTIAL_TYPE') }}"
        inputs:
          token: "{{ lookup('env','TOKEN_SECRET') }}"
        state: present
      register: credentials
  when:
    - lookup('env','KUBERNETES_BEARER_TOKEN') == ''
    - lookup('env','SSH_SECRET') == ''
    - lookup('env','USERNAME_SECRET') == ''
    - lookup('env','PASSWORD_SECRET') == ''
    - lookup('env','TOKEN_SECRET') != ''

  rescue:
    - name: Update status if creation resulted in an error
      k8s_status:
        api_version: tower.ansible.com/v1alpha1
        kind: AnsibleCredential
        name: "{{ lookup('env', 'ANSIBLECREDENTIAL_NAME') }}"
        namespace: "{{ lookup('env', 'ANSIBLECREDENTIAL_NAMESPACE') }}"
        status:
          isFinished: true
          AnsibleCredentialsResult:
            status: "error"
    - name: End playbook run
      meta: end_play

- name: Update AnsibleCredential status
  k8s_status:
    api_version: tower.ansible.com/v1alpha1
    kind: AnsibleCredential
    name: "{{ lookup('env', 'ANSIBLECREDENTIAL_NAME') }}"
    namespace: "{{ lookup('env', 'ANSIBLECREDENTIAL_NAMESPACE') }}"
    status:
      isFinished: true
      AnsibleCredentialsResult:
        changed: "{{ credentials.changed }}"
        failed: "{{ credentials.failed }}"
  when:
  - lookup('env','SSH_SECRET') == ''
  - lookup('env','KUBERNETES_BEARER_TOKEN') == ''
  - lookup('env','USERNAME_SECRET') == ''
  - lookup('env','PASSWORD_SECRET') == ''
  - lookup('env','TOKEN_SECRET') != ''
