- name: Define a schedule, if error update AnsibleSchedule status then end play
  block:
    - name: Launch schedule
      awx.awx.schedule:
        name: "{{ lookup('env','NAME') }}"
        rrule: "{{ lookup('env','RRULE') }}"
        state: "{{ lookup('env','STATE') | default('present') }}"
        unified_job_template: "{{ lookup('env','UNIFIED_JOB_TEMPLATE') }}"
      register: schedule
  rescue:
    - name: Update status if creation resulted in an error
      operator_sdk.util.k8s_status:
        api_version: tower.ansible.com/v1alpha1
        kind: AnsibleSchedule
        name: "{{ lookup('env', 'ANSIBLESCHEDULE_NAME') }}"
        namespace: "{{ lookup('env', 'ANSIBLESCHEDULE_NAMESPACE') }}"
        status:
          isFinished: true
          AnsibleCredentialsResult:
            status: "error"
    - name: End playbook run
      meta: end_play

- name: Update AnsibleSchedule status
  operator_sdk.util.k8s_status:
    api_version: tower.ansible.com/v1alpha1
    kind: AnsibleSchedule
    name: "{{ lookup('env', 'ANSIBLESCHEDULE_NAME') }}"
    namespace: "{{ lookup('env', 'ANSIBLESCHEDULE_NAMESPACE') }}"
    status:
      isFinished: true
      AnsibleScheduleResult:
        changed: "{{ schedule.changed }}"
