- name: Define credentials, if error update AnsibleCredential status then end play
  block:
    - name: Create Credential
      awx.awx.credential:
        name: "{{ lookup('env','CREDENTIAL_NAME') }}"
        description: "{{ lookup('env','CREDENTIAL_DESCRIPTION') }}"
        organization: "{{ lookup('env','CREDENTIAL_ORGANIZATION') }}"
        credential_type: "{{ lookup('env','CREDENTIAL_TYPE') }}"
        inputs: "{{ lookup('env','CREDENTIAL_INPUTS') }}"
        state: present
      register: credentials
  rescue:
    - name: Update status if creation resulted in an error
      k8s_status:
        api_version: tower.ansible.com/v1alpha1
        kind: AnsibleCredential
        name: "{{ lookup('env', 'ANSIBLECREDENTIAL_NAME') }}"
        namespace: "{{ lookup('env', 'ANSIBLECREDENTIAL_NAMESPACE') }}"
        status:
          AnsibleCredentialsResult:
            status: "error"
    - name: End playbook run
      meta: end_play

- name: Update AnsibleCredential status
  k8s_status:
    api_version: tower.ansible.com/v1alpha1
    kind: AnsibleCredential
    name: "{{ lookup('env', 'ANSIBLECREDENTIAL_NAME') }}"
    namespace: "{{ lookup('env', 'ANSIBLECREDENTIAL_NAMESPACE') }}"
    status:
      AnsibleCredentialsResult:
        changed: "{{ credentials.changed }}"
        failed: "{{ credentials.failed }}"
