- name: Launch SSH Credential
  include_tasks: credentials/create_ssh_credential.yml
  when:
    - lookup('env','SSH_SECRET') != ''
    - lookup('env','KUBERNETES_BEARER_TOKEN') == ''
    - lookup('env','USERNAME_SECRET') == ''
    - lookup('env','PASSWORD_SECRET') == ''
    - lookup('env','TOKEN_SECRET') == ''

- name: Launch Bearer Credential
  include_tasks: credentials/create_bearer_credential.yml
  when:
    - lookup('env','KUBERNETES_BEARER_TOKEN') != ''
    - lookup('env','SSH_SECRET') == ''
    - lookup('env','USERNAME_SECRET') == ''
    - lookup('env','PASSWORD_SECRET') == ''
    - lookup('env','TOKEN_SECRET') == ''

- name: Launch Username Credential
  include_tasks: credentials/create_userpass_credential.yml
  when:
    - lookup('env','KUBERNETES_BEARER_TOKEN') == ''
    - lookup('env','SSH_SECRET') == ''
    - lookup('env','USERNAME_SECRET') != ''
    - lookup('env','PASSWORD_SECRET') != ''
    - lookup('env','TOKEN_SECRET') == ''

- name: Launch Token Credential
  include_tasks: credentials/create_token_credential.yml
  when:
    - lookup('env','KUBERNETES_BEARER_TOKEN') == ''
    - lookup('env','SSH_SECRET') == ''
    - lookup('env','USERNAME_SECRET') == ''
    - lookup('env','PASSWORD_SECRET') == ''
    - lookup('env','TOKEN_SECRET') != ''

- name: Launch Generic Credential
  include_tasks: credentials/create_generic_credential.yml
  when:
    - lookup('env','SSH_SECRET') == ''
    - lookup('env','KUBERNETES_BEARER_TOKEN') == ''
    - lookup('env','USERNAME_SECRET') == ''
    - lookup('env','PASSWORD_SECRET') == ''
    - lookup('env','TOKEN_SECRET') == ''      