apiVersion: tower.ansible.com/v1alpha1
kind: WorkflowTemplate
metadata:
  name: workflowtemplate-broken
spec:
  tower_auth_secret: awxaccess
  workflow_template_name: BrokenTemplate
  workflow_template_description: Example Workflow Template
  workflow_template_organization: Default
  workflow_template_inventory: Demo Inventory
  workflow_nodes:
  - identifier: node101
    unified_job_template:
      name: Demo Job Template Missing
      inventory:
        organization:
          name: Default
      type: job_template
  - identifier: node102
    unified_job_template:
      name: Demo Job Template Missing
      inventory:
        organization:
          name: Default
      type: job_template
