# permissions for end users to view ansibleinstancegroups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ansibleinstancegroup-viewer-role
rules:
- apiGroups:
  - tower.ansible.com
  resources:
  - ansibleinstancegroups
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - tower.ansible.com
  resources:
  - ansibleinstancegroups/status
  verbs:
  - get
