# permissions for end users to view ansibleprojects.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ansibleproject-viewer-role
rules:
- apiGroups:
  - tower.ansible.com
  resources:
  - ansibleprojects
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - tower.ansible.com
  resources:
  - ansibleprojects/status
  verbs:
  - get
