# permissions for end users to view ansibleschedules.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ansibleschedule-viewer-role
rules:
- apiGroups:
  - tower.ansible.com
  resources:
  - ansibleschedules
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - tower.ansible.com
  resources:
  - ansibleschedules/status
  verbs:
  - get
