# permissions for end users to edit ansibleinstancegroups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ansibleinstancegroup-editor-role
rules:
- apiGroups:
  - tower.ansible.com
  resources:
  - ansibleinstancegroups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tower.ansible.com
  resources:
  - ansibleinstancegroups/status
  verbs:
  - get
