# permissions for end users to edit ansiblecredentials.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ansiblecredential-editor-role
rules:
- apiGroups:
  - tower.ansible.com
  resources:
  - ansiblecredentials
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tower.ansible.com
  resources:
  - ansiblecredentials/status
  verbs:
  - get
