# permissions for end users to edit ansibleprojects.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ansibleproject-editor-role
rules:
- apiGroups:
  - tower.ansible.com
  resources:
  - ansibleprojects
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tower.ansible.com
  resources:
  - ansibleprojects/status
  verbs:
  - get
