# permissions for end users to view ansiblecredentials.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ansiblecredential-viewer-role
rules:
- apiGroups:
  - tower.ansible.com
  resources:
  - ansiblecredentials
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - tower.ansible.com
  resources:
  - ansiblecredentials/status
  verbs:
  - get
