# permissions for end users to view ansibleworkflows.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ansibleworkflow-viewer-role
rules:
- apiGroups:
  - tower.ansible.com
  resources:
  - ansibleworkflows
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - tower.ansible.com
  resources:
  - ansibleworkflows/status
  verbs:
  - get
