# permissions for end users to view inventories.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: inventory-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: awx-resource-operator
    app.kubernetes.io/part-of: awx-resource-operator
    app.kubernetes.io/managed-by: kustomize
  name: inventory-viewer-role
rules:
- apiGroups:
  - tower.ansible.com
  resources:
  - inventories
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - tower.ansible.com
  resources:
  - inventories/status
  verbs:
  - get
