---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: jobtemplates.tower.ansible.com
spec:
  group: tower.ansible.com
  names:
    kind: JobTemplate
    listKind: JobTemplateList
    plural: jobtemplates
    singular: jobtemplate
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: Schema validation for the Tower Resource CRD
      properties:
        spec:
          properties:
            job_template_inventory:
              type: string
            job_template_name:
              type: string
            job_template_playbook:
              type: string
            job_template_project:
              type: string
            tower_auth_secret:
              type: string
          type: object
      required:
      - tower_auth_secret
      type: object
      x-kubernetes-preserve-unknown-fields: true
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
