apiVersion: tower.ansible.com/v1alpha1
kind: JobTemplate
metadata:
  name: jobtemplate-sample
spec:
  tower_auth_secret: awxaccess
  name: ExampleJobTemplate
  project: Demo Project
  playbook: hello_world.yml
  inventory: Demo Inventory
