apiVersion: operators.coreos.com/v1beta1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
    categories: Integration & Delivery,OpenShift Optional
    certified: "false"
    containerImage: quay.io/ansible/awx-resource-runner:latest
    description: The Ansible Automation Platform Resource Operator manages launching
      Ansible Jobs and Workflows.
    repository: https://github.com/ansible/awx-resource-operator
    support: Red Hat
  name: awx-resource-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: Launch a new job via awx
      displayName: AWX Job
      kind: AnsibleJob
      name: ansiblejobs.tower.ansible.com
      specDescriptors:
      - displayName: Job Template Name
        path: job_template_name
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - displayName: AWX Authentication Secret (DEPRECATED)
        path: tower_auth_secret
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - displayName: Authentication Secret
        path: connection_secret
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - displayName: AWX Inventory
        path: inventory
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - displayName: Extra Variables
        path: extra_vars
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - displayName: Job TTL
        path: job_ttl
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
        - urn:alm:descriptor:com.tectonic.ui:advanced
      - displayName: Job Tags
        path: job_tags
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
        - urn:alm:descriptor:com.tectonic.ui:advanced
      - displayName: Skip Tags
        path: skip_tags
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
        - urn:alm:descriptor:com.tectonic.ui:advanced
      - displayName: Ansible Runner Image
        path: runner_image
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
        - urn:alm:descriptor:com.tectonic.ui:advanced
      - displayName: Ansible Runner Version
        path: runner_version
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
        - urn:alm:descriptor:com.tectonic.ui:advanced
      version: v1alpha1
    - description: Define a Credential
      displayName: AWX Credential
      kind: AnsibleCredential
      name: ansiblecredentials.tower.ansible.com
      specDescriptors:
      - displayName: Credential Name
        path: name
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - displayName: Credential Type
        path: type
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - displayName: Credential Organization
        path: organization
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - displayName: Credential Description
        path: description
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - displayName: Credential Inputs
        path: inputs
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - displayName: SSH Key Secret
        path: ssh_secret
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - displayName: Kubernetes Bearer Token Secret
        path: kubernetes_bearer_token_secret
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - displayName: Connection Secret
        path: connection_secret
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - displayName: Kubernetes API
        path: kubernetes_api
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - displayName: SSH Username
        path: ssh_username
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - displayName: Ansible Runner Image
        path: runner_image
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
        - urn:alm:descriptor:com.tectonic.ui:advanced
      - displayName: Ansible Runner Version
        path: runner_version
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
        - urn:alm:descriptor:com.tectonic.ui:advanced
      version: v1alpha1
    - description: Define an Instance Group
      displayName: AWX Instance Group
      kind: AnsibleInstanceGroup
      name: ansibleinstancegroupss.tower.ansible.com
      specDescriptors:
      - displayName: Instance Group Name
        path: name
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - displayName: OpenShift or Kubernetes credential
        path: credential_name
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - displayName: Container Group
        path: is_container_group
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:booleanSwitch
      - displayName: Policy Spec Override
        path: policy_spec_override
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - displayName: Policy Instance Percentage
        path: policy_instance_percentage
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:int
      - displayName: Policy Instance Minimum
        path: policy_instance_minimum
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:int
      - displayName: Instances for Group
        path: instance_list
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:array
      - displayName: Connection Secret
        path: connection_secret
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - displayName: Ansible Runner Image
        path: runner_image
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
        - urn:alm:descriptor:com.tectonic.ui:advanced
      - displayName: Ansible Runner Version
        path: runner_version
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
        - urn:alm:descriptor:com.tectonic.ui:advanced
      version: v1alpha1
    - description: Launch a new workflow via awx
      displayName: AWX Workflow
      kind: AnsibleWorkflow
      name: ansibleworkflows.tower.ansible.com
      specDescriptors:
      - displayName: Workflow Template Name
        path: workflow_template_name
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - displayName: Authentication Secret
        path: connection_secret
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - displayName: AWX Inventory
        path: inventory
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - displayName: Extra Variables
        path: extra_vars
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - displayName: Workflow TTL
        path: workflow_ttl
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
        - urn:alm:descriptor:com.tectonic.ui:advanced
      - displayName: Ansible Runner Image
        path: runner_image
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
        - urn:alm:descriptor:com.tectonic.ui:advanced
      - displayName: Ansible Runner Version
        path: runner_version
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
        - urn:alm:descriptor:com.tectonic.ui:advanced
      version: v1alpha1
    - description: Define a new job template in awx
      displayName: AWX Job Template
      kind: JobTemplate
      name: jobtemplates.tower.ansible.com
      specDescriptors:
      - displayName: Job Template Name
        path: job_template_name
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - displayName: AWX Authentication Secret(DEPRECATED)
        path: tower_auth_secret
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - displayName: Authentication Secret
        path: connection_secret
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - displayName: Job Template Inventory
        path: job_template_inventory
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - displayName: Job Template Playbook
        path: job_template_playbook
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - displayName: Job Template Project
        path: job_template_project
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - displayName: Job Template Ask Vars
        path: job_template_ask_vars
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - displayName: Job Template Ask Inventory
        path: job_template_ask_inventory
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      version: v1alpha1
    - description: Define a new workflow template
      displayName: AWX Workflow Template
      kind: WorkflowTemplate
      name: workflowtemplates.tower.ansible.com
      specDescriptors:
      - displayName: Workflow Template Name
        path: name
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - displayName: Authentication Secret
        path: connection_secret
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - displayName: Workflow Inventory
        path: inventory
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - displayName: Workflow Organization
        path: organization
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - displayName: Allow Simultaneous
        path: allow_simultaneous
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:booleanSwitch
      - displayName: Ask Inventory on launch
        path: ask_inventory_on_launch
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:booleanSwitch
      - displayName: Ask Variables on launch
        path: ask_variables_on_launch
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:booleanSwitch
      - displayName: Ask limit on launch
        path: ask_limit_on_launch
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:booleanSwitch
      - displayName: Ask scm branch on launch
        path: ask_scm_branch_on_launch
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:booleanSwitch
      - displayName: Ask labels on launch
        path: ask_labels_on_launch
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:booleanSwitch
      - displayName: Ask tags on launch
        path: ask_tags_on_launch
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:booleanSwitch
      - displayName: Ask skip tags on launch
        path: ask_skip_tags_on_launch
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:booleanSwitch
      - displayName: Workflow limit
        path: limit
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - displayName: Job tags
        path: job_tags
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - displayName: Labels for the template
        path: labels
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - displayName: Skip Tags
        path: skip_tags
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - displayName: Workflow description
        path: description
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - displayName: Survey Enabled
        path: survey_enabled
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:booleanSwitch
      - displayName: Survey Spec
        path: survey_spec
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
    - description: Define a new project in awx
      displayName: AWX Project
      kind: AnsibleProject
      name: ansibleprojects.tower.ansible.com
      specDescriptors:
      - displayName: Project Name
        path: name
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - displayName: Authentication Secret
        path: connection_secret
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - displayName: Git Repository URL
        path: repo
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - displayName: Git Repository Branch
        path: branch
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - displayName: Project Organization
        path: organization
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - displayName: Project SCM Type
        path: scm_type
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - displayName: Project Description
        path: description
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      version: v1alpha1
    - description: Define a new Schedule in awx
      displayName: AWX Schedule
      kind: AnsibleSchedule
      name: ansibleschedules.tower.ansible.com
      specDescriptors:
      - displayName: Schedule Name
        path: name
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - displayName: Authentication Secret
        path: connection_secret
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - displayName: Schedule Rules
        path: rrules
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - displayName: Unified Job Template
        path: unified_job_template
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      version: v1alpha1
  description: The Ansible Automation Platform Resource Operator manages launching
    Ansible Jobs and Workflows.
  displayName: AWX Resource Operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: true
    type: MultiNamespace
  - supported: false
    type: AllNamespaces
  keywords:
  - automation
  - ansible
  - controller
  - tower
  - awx
  - resource
  - ci
  - cd
  links:
  - name: AWX Resource Operator
    url: https://github.com/ansible/awx-resource-operator
  maintainers:
  - email: ocm-dev@open-cluster-management.io
    name: Open Cluster Management Project team
  maturity: alpha
  provider:
    name: Red Hat
    url: github.com/ansible/awx-resource-operator
  version: 0.0.0
