apiVersion: operators.coreos.com/v1beta1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
    categories: Integration & Delivery,OpenShift Optional
    certified: "false"
    containerImage: quay.io/open-cluster-management/platform-resource-operator:latest
    description: The Ansible Automation Platform Resource Operator manages launching
      Ansible Jobs and Workflows.
    repository: https://github.com/ansible/awx-resource-operator
    support: Red Hat
  name: awx-resource-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: Launch a new job via awx
      displayName: AWX job
      kind: AnsibleJob
      name: ansiblejobs.tower.ansible.com
      specDescriptors:
      - displayName: Job Template Name
        path: job_template_name
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - displayName: AWX Authentication Secret
        path: tower_auth_secret
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - displayName: AWX Inventory
        path: inventory
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - displayName: Extra Variables
        path: extra_vars
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - displayName: Job TTL
        path: job_ttl
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
        - urn:alm:descriptor:com.tectonic.ui:advanced
      - displayName: Ansible Runner Image
        path: runner_image
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
        - urn:alm:descriptor:com.tectonic.ui:advanced
      - displayName: Ansible Runner Version
        path: runner_version
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
        - urn:alm:descriptor:com.tectonic.ui:advanced
      version: v1alpha1
    - description: Define a new job template in awx
      displayName: AWX job template
      kind: JobTemplate
      name: jobtemplates.tower.ansible.com
      specDescriptors:
      - displayName: Job Template Name
        path: job_template_name
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - displayName: AWX Authentication Secret
        path: tower_auth_secret
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - displayName: Job Template Inventory
        path: job_template_inventory
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - displayName: Job Template Playbook
        path: job_template_playbook
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - displayName: Job Template Project
        path: job_template_project
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - displayName: Job Template Ask Vars
        path: job_template_ask_vars
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - displayName: Job Template Ask Inventory
        path: job_template_ask_inventory
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      version: v1alpha1
    - description: Define a new project in awx
      displayName: AWX project
      kind: AnsibleProject
      name: ansibleprojects.tower.ansible.com
      specDescriptors:
      - displayName: Project Name
        path: project_name
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - displayName: AWX Authentication Secret
        path: tower_auth_secret
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - displayName: Git Repository URL
        path: project_repo
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - displayName: Git Repository Branch
        path: project_branch
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - displayName: Project Organization
        path: project_organization
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - displayName: Project Description
        path: project_description
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text  
      version: v1alpha1
  description: The Ansible Automation Platform Resource Operator manages launching
    Ansible Jobs and Workflows.
  displayName: AWX Resource Operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: true
    type: MultiNamespace
  - supported: false
    type: AllNamespaces
  keywords:
  - automation
  - ansible
  - controller
  - tower
  - awx
  - resource
  - ci
  - cd
  links:
  - name: AWX Operator
    url: https://github.com/ansible/awx-resource-operator
  maintainers:
  - email: ocm-dev@open-cluster-management.io
    name: Open Cluster Management Project team
  maturity: alpha
  provider:
    name: Red Hat
    url: github.com/ansible/awx-resource-operator
  version: 0.0.0
