apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: awx-resource-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions: {}
  description: The AWX Resource Operator manages launching Ansible Jobs and Workflows.
  displayName: AWX Resource Operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - tower
  - resource
  - awx
  - ansible
  - automation
  - ci
  - cd
  - deployment
  links:
  - name: Awx Resource Operator
    url: https://awx-resource-operator.domain
  maturity: alpha
  provider:
    name: Red Hat
    url: https://github.com/ansible/awx-resource-operator
  version: 0.0.0
