---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tower-resource-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: tower-resource-operator
  template:
    metadata:
      labels:
        name: tower-resource-operator
    spec:
      serviceAccountName: tower-resource-operator
      containers:
        - name: tower-resource-operator
          # Replace this with the built image name
          image: "matburt/tower-resource-operator:0.1.0"
          imagePullPolicy: "Always"
          volumeMounts:
          - mountPath: /tmp/ansible-operator/runner
            name: runner
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "tower-resource-operator"
            - name: ANSIBLE_GATHERING
              value: explicit
            - name: ANSIBLE_DEBUG_LOGS
              value: "True"
      volumes:
        - name: runner
          emptyDir: {}
