---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tower-resource-operator
  namespace: tower-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: tower-resource-operator
  template:
    metadata:
      labels:
        name: tower-resource-operator
    spec:
      serviceAccountName: tower-resource-operator
      containers:
        - name: tower-resource-operator
          # Replace this with the built image name
          image: "quay.io/open-cluster-management/platform-resource-operator:latest"
          imagePullPolicy: "Always"
          volumeMounts:
          - mountPath: /tmp/ansible-operator/runner
            name: runner
          env:
            - name: WATCH_NAMESPACE
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "tower-resource-operator"
            - name: ANSIBLE_GATHERING
              value: explicit
            - name: ANSIBLE_DEBUG_LOGS
              value: "True"
            - name: RELATED_IMAGE_ANSIBLE_JOB_RUNNER_IMAGE
              # Replace this with the job runner built image name
              value: "quay.io/open-cluster-management/platform-resource-runner:latest"
      volumes:
        - name: runner
          emptyDir: {}
