apiVersion: tower.ansible.com/v1alpha1
kind: AnsibleCredential
metadata:
  name: bearer-cred
spec:
  name: bearer-cred
  organization: Default
  connection_secret: awxaccess
  description: "Bearer Credential"
  type: "OpenShift or Kubernetes API Bearer Token"
  kubernetes_api: https://notarealurl.com:6443
  kubernetes_bearer_token_secret: bearer-secret
  runner_pull_policy: IfNotPresent
