apiVersion: tower.ansible.com/v1alpha1
kind: AnsibleCredential
metadata:
  name: scm-cred
spec:
  credential_name: scm-cred
  credential_organization: Default
  connection_secret: awxaccess
  credential_description: "This is a source control cred"
  credential_type: "Source Control"
  username_secret: github-secret
  password_secret: github-secret
  runner_pull_policy: IfNotPresent
