apiVersion: tower.ansible.com/v1alpha1
kind: AnsibleCredential
metadata:
  name: cr-cred
spec:
  name: container-registry-access
  organization: Default
  connection_secret: awxaccess
  description: "This is a test container registry credential"
  type: "Container Registry"
  username_secret: cr-secret
  password_secret: cr-secret
  container_registry_host: registry.example.com
  runner_pull_policy: IfNotPresent
