apiVersion: tower.ansible.com/v1alpha1
kind: AnsibleCredential
metadata:
  name: sc-cred
spec:
  credential_name: sc-cred 
  credential_organization: Default
  tower_auth_secret: awxaccess
  credential_description: "This is a source control cred"
  credential_type: "Source Control"
  credential_inputs: "{'username': 'test', 'password': 'test'}"
  runner_pull_policy: IfNotPresent
