apiVersion: tower.ansible.com/v1alpha1
kind: AnsibleCredential
metadata:
  name: bearer-cred
spec:
  credential_name: bearer-cred
  credential_organization: Default
  tower_auth_secret: awxaccess
  credential_description: "Bearer Credential"
  credential_type: "OpenShift or Kubernetes API Bearer Token"
  kubernetes_api: https://notarealurl.com:6443
  kubernetes_bearer_secret: bearer-secret
  runner_pull_policy: IfNotPresent
