apiVersion: tower.ansible.com/v1alpha1
kind: AnsibleCredential
metadata:
  name: scm-cred
spec:
  name: scm-cred
  organization: Default
  connection_secret: awxaccess
  description: "This is a source control cred"
  type: "Source Control"
  username_secret: github-secret
  password_secret: github-secret
  runner_pull_policy: IfNotPresent
