## Append samples you want in your CSV to this file as resources ##
resources:
- tower_v1alpha1_ansiblejob.yaml
- tower_v1alpha1_jobtemplate.yaml
- tower_v1alpha1_ansibleworkflow.yaml
- tower_v1alpha1_ansiblecredential.yaml
#+kubebuilder:scaffold:manifestskustomizesamples
