apiVersion: tower.ansible.com/v1alpha1
kind: JobTemplate
metadata:
  name: jobtemplate-sample
spec:
  tower_auth_secret: controller-access-secret
  job_template_name: ExampleJobTemplate
  job_template_project: Demo Project
  job_template_playbook: hello_world.yml
  job_template_inventory: Demo Inventory
