apiVersion: tower.ansible.com/v1alpha1
kind: AnsibleExecutionEnvironment
metadata:
  labels:
    app.kubernetes.io/name: ansibleexecutionenvironment
    app.kubernetes.io/instance: ansibleexecutionenvironment-sample
    app.kubernetes.io/part-of: awx-resource-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: awx-resource-operator
  name: ansibleexecutionenvironment-sample
spec:
  # TODO(user): Add fields here
