apiVersion: tower.ansible.com/v1alpha1
kind: AnsibleCredentials
metadata:
  name: ansible-credentials-sample
spec:
  credential_name: aws-access
  credential_organization: Default
  tower_auth_secret: awx-access
  credential_description: "This is a test credential"
  credential_type: "Amazon Web Services"
  credential_inputs: "{'username': 'test', 'password': 'test'}"
