apiVersion: tower.ansible.com/v1alpha1
kind: AnsibleInventory
metadata:
  name: inventory-new
spec:
  connection_secret: awxaccess
  description: my new inventory
  name: newinventory
  organization: Default
  state: present
  instance_groups: default
