---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - github.com/ansible/awx-operator/config/default?ref=TAG
images:
  - name: quay.io/ansible/awx-operator
    newTag: TAG
namespace: awx
