---
apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: null
  name: awx-resource-secret
  namespace: awx
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: awx-resource-secret 
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - create
  - delete
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
  name: resource-operator-token-binding 
  namespace: awx
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: awx-resource-secret
subjects:
- kind: ServiceAccount
  name: awx-resource-secret
  namespace: awx
---
apiVersion: batch/v1
kind: Job
metadata:
  name: create-token
  namespace: awx
spec:
  backoffLimit: 1
  template:
    spec:
      serviceAccountName: awx-resource-secret
      containers:
      - name: token
        imagePullPolicy: IfNotPresent
        image: quay.io/ansible/token-playbook:latest
        command: ["/usr/local/bin/ansible-playbook",  "/runner/playbook.yaml"]
        env:
        - name: ADMIN
          value: admin
        - name: CREDENTIAL
          valueFrom:
            secretKeyRef:
              name: awx-demo-admin-password
              key: password
      restartPolicy: Never
