---

- name: Read Secret Configuration
  k8s_info:
    kind: Secret
    namespace: '{{ ansible_operator_meta.namespace }}'
    name: "{{ tower_auth_secret }}"
  register: tower_config_secret

- name: Validate Secret Exists
  assert:
    that:
      - tower_config_secret["resources"] is defined and (tower_config_secret["resources"]|length>0)
    fail_msg: "Tower Secret must exist"

- name: Show secret details
  debug:
    msg: "{{ tower_config_secret }}"
  no_log: true

- name: Create Workflow Template
  awx.awx.workflow_job_template:
    name: "{{ workflow_template_name }}"
    description: "{{ workflow_template_description }}"
    organization: "{{ workflow_template_organization }}"
    inventory: "{{ workflow_template_inventory | default(omit) }}"
    extra_vars: "{{ workflow_template_extra_vars | default(omit) }}"
    workflow_nodes: "{{ workflow_nodes }}"
  environment:
    - TOWER_OAUTH_TOKEN: "{{ tower_config_secret['resources'][0]['data']['token'] | b64decode }}"
    - TOWER_HOST: "{{ tower_config_secret['resources'][0]['data']['host'] | b64decode }}"
    - TOWER_VERIFY_SSL: "False"
