---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: jobtemplates.tower.ansible.com
spec:
  group: tower.ansible.com
  names:
    kind: JobTemplate
    listKind: JobTemplateList
    plural: jobtemplates
    singular: jobtemplate
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
          description: Schema validation for the Tower Resource CRD
          properties:
            spec:
              type: object
              properties:
                tower_auth_secret:
                  type: string
                job_template_name:
                  type: string
                job_template_project:
                  type: string
                job_template_playbook:
                  type: string
                job_template_inventory:
                  type: string
          required:
            - tower_auth_secret
