---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: ansibleprojects.tower.ansible.com
spec:
  group: tower.ansible.com
  names:
    kind: AnsibleProject
    listKind: AnsibleProjectList
    plural: ansibleprojects
    singular: ansibleproject
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: (Tech Preview) AnsibleProject is the Schema for the ansibleprojects API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            properties:
              repo:
                type: string
                description: The URL of the project resources
              branch:
                type: string
                description: The branch of the project repository
              name:
                type: string
                description: The name of the project
              organization:
                type: string
                description: The organization of the project
              scm_credential:
                type: string
                description: The SCM credential for the project
              scm_type:
                type: string
                description: The SCM type of the project
              description:
                type: string
                description: The description of the project
              connection_secret:
                description: |
                  A k8s secret that contains an access token for AWX. To create an access token see these docs: https://docs.ansible.com/automation-controller/4.1.0/html/userguide/applications_auth.html#add-tokens.
                type: string
              runner_image:
                type: string
                description: Runner image used when running jobs
              runner_version:
                type: string
                description: Runner image version used when running jobs
              runner_pull_policy:
                type: string
                description: Runner image pull policy used when running jobs
            required:
            - connection_secret
            - scm_type
            - name
            - organization
            description: Spec defines the definition of the AnsibleProject
            type: object
            x-kubernetes-preserve-unknown-fields: true
          status:
            description: Status defines the observed state of AnsibleProject
            type: object
            x-kubernetes-preserve-unknown-fields: true
        type: object
    served: true
    storage: true
    subresources:
      status: {}
