---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: ansibleprojects.tower.ansible.com
spec:
  group: tower.ansible.com
  names:
    kind: AnsibleProject
    listKind: AnsibleProjectList
    plural: ansibleprojects
    singular: ansibleproject
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: AnsibleProject is the Schema for the ansibleprojects API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            properties:
              project_repo:
                type: string
                description: The URL of the project repository
              project_branch:
                type: string
                description: The branch of the project repository
              project_name:
                type: string
                description: The name of the project
              project_organization:
                type: string
                description: The organization of the project
              tower_auth_secret:
                description: |
                  A k8s secret that contains an access token for AWX. To create an access token see these docs: https://docs.ansible.com/automation-controller/4.1.0/html/userguide/applications_auth.html#add-tokens.
                type: string
          status:
            description: Status defines the observed state of AnsibleProject
            type: object
            x-kubernetes-preserve-unknown-fields: true
        type: object
    served: true
    storage: true
    subresources:
      status: {}
