---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: workflowtemplates.tower.ansible.com
spec:
  group: tower.ansible.com
  names:
    kind: WorkflowTemplate
    listKind: WorkflowTemplateList
    plural: workflowtemplates
    singular: workflowtemplate
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: WorkflowTemplate is the Schema for the workflowtemplates API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            properties:
              tower_auth_secret:
                description: Tower Auth Secret is the name of the secret containing the
                  username and password for the Tower instance
                type: string
              workflow_template_name:
                description: Workflow Template Name is the name of the workflow template
                  in Tower
                type: string
              workflow_template_extra_vars:
                description: Workflow Template Extra Vars is a list of extra vars to
                  be passed to the workflow template in Tower
                type: object
                x-kubernetes-preserve-unknown-fields: true
              workflow_template_description:
                description: Workflow Template Description is the description of the
                  workflow template in Tower
                type: string
              workflow_template_organization:
                description: Workflow Template Organization is the name of the organization
                  in Tower
                type: string
              workflow_template_inventory:
                description: Workflow Template Inventory is the name of the inventory
                  in Tower
                type: string
            required:
            - tower_auth_secret
            - workflow_template_name
            - workflow_template_description
            - workflow_template_organization
            - workflow_template_inventory
            - workflow_nodes
            description: Spec defines the desired state of WorkfkowTemplate
            type: object
            x-kubernetes-preserve-unknown-fields: true
          status:
            description: Status defines the observed state of WorkflowTemplate
            type: object
            x-kubernetes-preserve-unknown-fields: true
        type: object
    served: true
    storage: true
    subresources:
      status: {}