---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: ansiblecredentials.tower.ansible.com
spec:
  group: tower.ansible.com
  names:
    kind: AnsibleCredential
    listKind: AnsibleCredentialList
    plural: ansiblecredentials
    singular: ansiblecredential
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: AnsibleCredential is the Schema for the ansiblecredentials API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            properties:
              credential_name:
                type: string
                description: The name for the credential
              credential_organization:
                type: string
                description: The organization for the credential
              runner_image:
                type: string
                description: Runner image used when running jobs
              runner_version:
                type: string
                description: Runner image version used when running jobs
              runner_pull_policy:
                type: string
                description: Runner image pull policy used when running jobs
              credential_description:
                type: string
                description: The description for the credential
              credential_type:
                type: string
                description: The credential type for the credential
              credential_inputs:
                type: string
                description: The credential inputs for the credential
              tower_auth_secret:
                description: |
                  A k8s secret that contains an access token for AWX. To create an access token see these docs: https://docs.ansible.com/automation-controller/4.1.0/html/userguide/applications_auth.html#add-tokens.
                type: string
            required:
            - tower_auth_secret
            - credential_name
            - credential_organization
            - credential_description
            - credential_type
            - credential_inputs
            description: Spec defines the definition of the AnsibleCredential
            type: object
            x-kubernetes-preserve-unknown-fields: true
          status:
            description: Status defines the observed state of AnsibleCredential
            type: object
            x-kubernetes-preserve-unknown-fields: true
        type: object
    served: true
    storage: true
    subresources:
      status: {}
